config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 5, maximimum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email, :id
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image


  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank?}


  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates_presence_of :title, :precent_untitled
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  validates_presence_of :name

  has_many :comments, dependent: :destroy

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])

    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if  @blog.draft?
      @blog.published!
    elsif  @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body,
       technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your post is now live.'}
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    # Perform the lookup
    @portfolio_item = Blog.find(params[:id])

    # Destroy/delete the record
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Post was successfully destroyed.' }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sidebar_topics
  layout 'blog'

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])

    if logged_in?(:site_admin)
      @blogs = @topic.blogs.recent.page(params[:page]).per(5)
    else
      @blogs = @topic.blogs.published.recent.page(params[:page]).per(5)
    end
  end

  private

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if current_user %>
     <%= link_to "Logout", destroy_user_session_path, method: :delete %>
   <% else %>
    <%= link_to "Register", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Slab" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/blog_nav' %>
    <%= render 'shared/blog_masthead' %>

    <div class="container">

      <div class="row">

        <%= yield %>

        <%= render 'shared/blog_sidebar' %>
      </div>

      <%= render 'shared/blog_footer' %>

      <%= alerts %>
    </div>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/portfolio_nav' %>
    <%= render 'shared/portfolio_masthead' unless logged_in?(:site_admin) %>

    <%= yield %>

    <%= render 'shared/portfolio_footer' %>

    <%= alerts %>
  </body>
</html>

app/views/pages/_about_buttons.html.erb
          <button
            class="btn btn-primary"
            type="button"
            data-toggle="collapse"
            data-target="#jobHistory"
            aria-expanded="false"
            aria-controler="jobHistory"
          >
            Job History
          </button>

          <button
            class="btn btn-primary"
            type="button"
            data-toggle="collapse"
            data-target="#education"
            aria-expanded="false"
            aria-controler="education"
          >
            Education
          </button>

          <button
            class="btn btn-primary"
            type="button"
            data-toggle="collapse"
            data-target="#courses"
            aria-expanded="false"
            aria-controler="courses"
          >
            Courses Developed
          </button>

          <button
            class="btn btn-primary"
            type="button"
            data-toggle="collapse"
            data-target="#press"
            aria-expanded="false"
            aria-controler="press"
            >
            Press 
          </button>

app/views/pages/_about_courses.html.erb
          <div class="collapse" id="courses">
            <div class="card card-block">
              <div class="row">
                <div class="col-md-4">
                  <%= image_tag 'about/courses_rails_5.jpg', width: '100%' %>
                  <%= link_to "Dissecting Rails 5", root_path %>
                </div>
                <div class="col-md-4">
                  <%= image_tag 'about/courses_angular.jpg', width: '100%' %>
                  <%= link_to "Angular + Rails", "https://www.udemy.com/angular-on-rails-course/", target: '_blank' %>
                </div>
                <div class="col-md-4">
                  <%= image_tag 'about/courses_ruby.jpg', width: '100%' %>
                  <%= link_to "Comprehensive Ruby", "https://www.udemy.com/comprehensive-ruby-programming-tutorial/", target: '_blank' %>
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-4">
                  <%= image_tag 'about/courses_tdd_bdd.jpg', width: '100%' %>
                  <%= link_to "Professional Rails Code Along", "https://www.udemy.com/professional-ruby-on-rails-coding-course/", target: '_blank' %>
                </div>
                <div class="col-md-4">
                  <%= image_tag 'about/courses_vim.jpg', width: '100%' %>
                  <%= link_to "Vim for Ruby Developers", "https://www.udemy.com/vim-training-course-ruby-developers/", target: '_blank' %>
                </div>
                <div class="col-md-4">
                  <%= image_tag 'about/courses_ts.jpg', width: '100%' %>
                  <%= link_to "TypeScript Development", "https://www.udemy.com/introduction-typescript-development/", target: '_blank' %>
                </div>
              </div>
            </div>
          </div>

app/views/pages/_about_education.html.erb
          <div class="collapse" id="education">
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/ttu.png', width: '100%' %>
                </div>
                <div class="col-md-9">
                  Currently in Graduate School in the Texas Tech University Computer Science program studying machine learning.
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/grantham.png', width: '100%' %>
                </div>
                <div class="col-md-9">
                  Graduated Magna Cum Laude from Grantham University with a BS in Computer Science.
                </div>
              </div>
            </div>
          </div>

app/views/pages/_about_job_history.html.erb
          <div class="collapse" id="jobHistory">
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/devcamp.png', width: '100%' %>
                </div>
                <div class="col-md-9">
                  <strong>CTO</strong> - Lead in the development of the devCamp Learning Management System along with curriculum development from founding to acquisition.
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/w_blue.png', width: '100%' %>
                </div>
                <div class="col-md-9">
                  <strong>VP Engineering</strong> - Managed development department for Wilson Systems and lead in the build out of a number of enterprise web and mobile applications.
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/slate.png', width: '100%' %>
                </div>
                <div class="col-md-9">
                  <strong>Chief Architect</strong> - Lead in the planning of a number of key development projects.
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'about/bottega.jpg', width: '100%' %>
                </div>
                <div class="col-md-9">
                  <strong>Curriculum Director</strong> - Developed the curriculum for the Bottega Code School, including courses on: Ruby on Rails, Algorithms & Data Structures, Front End Coding, and Database Management.
                </div>
              </div>
            </div>
          </div>

app/views/pages/_about_press.html.erb
          <div class="collapse" id="press">
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'RubyRogues', "https://devchat.tv/ruby-rogues/mrs-008-jordan-hudgens", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  My Ruby Story - Jordan Hudgens
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'RubyRogues', "https://devchat.tv/ruby-rogues/rr-318-metaprogramming-jordan-hudgens", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Practical Metaprogramming
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Forbes', "https://www.forbes.com/sites/larrymyler/2017/04/25/how-a-solution-to-one-of-your-problems-could-be-your-next-business/#4fd543cd5ac5", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  How A Solution To One Of Your Problems Could Be Your Next Business
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'CIO', "http://www.cio.com/article/2394667/careers-staffing/14-tips-to-help-new-college-grads-land-a--good--it-job.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  14 Tips to Help New College Grads Land a (Good) IT Job
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Udemy', "https://blog.udemy.com/ruby-on-rails-tutorial-learn-from-scratch/", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Ruby on Rails Tutorial: Learn From Scratch
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'NG Data', "https://www.ngdata.com/big-data-technology-trends-in-banking/#Hudgens", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  20 experts reveal the most important big data technology trends shaping banking and finance today
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'SmartFile', "http://www.smartfile.com/blog/8-questions-hiring-dream-software-developer/", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  8 Questions to Hiring Your Dream Software Developer
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'The Street', "https://www.thestreet.com/story/13667907/1/can-you-bring-your-significant-other-on-a-business-trip.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Can You Bring Your Significant Other on a Business Trip?
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Computer User UK', "http://www.computerworlduk.com/galleries/it-business/10-technologies-that-changed-business-forever-3370249/", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  10 technologies that changed business forever
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Ecommerce Times', "http://www.ecommercetimes.com/story/64171.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  The Legal Perils of Social Networking
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Ecommerce Times', "http://www.ecommercetimes.com/story/64171.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  The Legal Perils of Social Networking
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'TechTarget', "http://searchsqlserver.techtarget.com/news/2240148415/Big-data-a-big-deal-for-SQL-Server-2012-users-say", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Big data a big deal for SQL Server 2012, users say
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Minyanville', "http://www.minyanville.com/sectors/consumer/articles/AAPL-GOOG-MSFT-NOK-AMZN-YHOO/9/27/2012/id/44482?page=2", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Who’s the Winner and Loser in the Apple / Google Maps War?
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Ecommerce Times', "http://www.ecommercetimes.com/rsstory/63636.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Google Media Server: A Giant Toe in the Door [Ecommerce Times]
                </div>
              </div>
            </div>
            <div class="card card-block">
              <div class="row">
                <div class="col-md-2">
                  <%= link_to 'Blue Print Hollywood', "http://www.frontgatemedia.com/news/biola2008_2.html", target: '_blank' %>
                </div>
                <div class="col-md-10">
                  Biola Media Conference Speaking Appearance: Designing for the Digital Age
                </div>
              </div>
            </div>
          </div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Homepage</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/pages/tech_news.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Rails News</h1>
  
  <div class="row">
    <% @tweets.each do |tweet| %>
      <div class="col-md-6">
        <div class="tech-news">
          <div class="card">
            <%= twitter_parser tweet %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Jordan Hudgens</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Dev Thoughts</h1>
    <p class="lead blog-description">Musings from my development journey.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Jordan Hudgens", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About Me</h4>
    <p>
      Teaching is both my passion and my best ally for mastery.
    </p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/jordanhudgens"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/jordanhudgens/"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://twitter.com/jordanhudgens"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These application capture a wide range of the applications that love to develop, including: web and mobile applications, enterprise projects, machine learning projects, and tools used by millions of users each day.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Jordan Hudgens", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>